# **WEB USAGE**

##**Filter Data Berdasarkan Ekstensi .html**

In [4]:
import pandas as pd
from IPython.display import display

file_name = "webusage.csv" # Mengoreksi nama file dari "webuage.csv" menjadi "webusage.csv"

print(f"Memuat data dari {file_name}...")

# Gunakan pemisah koma karena header menunjukkan koma
df = pd.read_csv(file_name, sep=',')

print("\nDaftar kolom dalam dataset:")
print(df.columns.tolist())

print("\nInfo data asli:")
df.info()

print("\nData asli (head):")
display(df.head())

# Tentukan kolom target yang sekarang pasti terbaca
target_column = "Request URI"

if target_column not in df.columns:
    print(f"\n❌ Kolom '{target_column}' tidak ditemukan!")
else:
    print(f"\nMemfilter data pada kolom '{target_column}' yang berakhiran '.html'...")

    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    output_filename = "html_requests_only.csv"
    filtered_df.to_csv(output_filename, index=False)

    print(f"\n✅ Berhasil menyimpan hasil filter ke '{output_filename}'.")
    display(filtered_df.head())

Memuat data dari webusage.csv...

Daftar kolom dalam dataset:
['Remote host', 'Remote logname', 'Remote user', 'Request time', 'Request method', 'Request URI', 'Request Protocol', 'Status', 'Size of response (incl. headers)']

Info data asli:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132258 entries, 0 to 132257
Data columns (total 9 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Remote host                       132258 non-null  object
 1   Remote logname                    132258 non-null  object
 2   Remote user                       132258 non-null  object
 3   Request time                      132258 non-null  object
 4   Request method                    132258 non-null  object
 5   Request URI                       132258 non-null  object
 6   Request Protocol                  132258 non-null  object
 7   Status                            132258 non-null  int64
 8   Size of response (incl. headers)  132258 non-null  int64
dtypes: int64(2), object(7)
memory usage: 9.1+ MB

Data asli (head):

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers)
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946
3,72.30.57.238,-,-,2009-10-15T02:01:59Z,GET,/contribute.txt,HTTP/1.0,200,39943
4,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247

Memfilter data pada kolom 'Request URI' yang berakhiran '.html'...

✅ Berhasil menyimpan hasil filter ke 'html_requests_only.csv'.

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers)
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946
4,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247
5,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883

## **Filter Dengan Status 200**

In [5]:
file_name = "html_requests_only.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Tentukan kolom target
target_column = "Status"

# 3. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 4. Periksa apakah kolomnya numerik
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # 5. Filter baris di mana 'Status' = 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")
        filtered_df = df[df[target_column] == 200].copy()

        # 6. Simpan data hasil filter
        output_filename = "status_200_only.csv"
        filtered_df.to_csv(output_filename, index=False)

        # 7. Tampilkan hasil dalam kotak tabel
        print(f"\nBerhasil memfilter data dan menyimpannya ke '{output_filename}'.")
        print("Pratinjau data yang telah difilter:")
        display(filtered_df.head())

    else:
        print(f"Error: Kolom '{target_column}' bukan numerik. Tidak dapat memfilter berdasarkan nilai 200.")

Memuat data dari html_requests_only.csv...

Memfilter data untuk baris di mana 'Status' adalah 200...

Berhasil memfilter data dan menyimpannya ke 'status_200_only.csv'.
Pratinjau data yang telah difilter:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers)
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946
3,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247
4,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883

## **Mengambil Data Berdasarkan Request Method = GET**

In [6]:
file_name = "status_200_only.csv"
filter_value = "GET"
target_column = "Request method"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Filter baris di mana 'Request method' sama dengan 'GET'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")

    filtered_df = df[df[target_column] == filter_value].copy()

    # 4. Simpan data yang telah difilter ke file CSV baru
    output_filename = "method_get_only.csv"
    filtered_df.to_csv(output_filename, index=False)

    # 5. Tampilkan hasil dalam tabel rapi
    print(f"\nBerhasil memfilter data dan menyimpannya ke '{output_filename}'.")
    print("Pratinjau data yang telah difilter:")
    display(filtered_df.head())

Memuat data dari status_200_only.csv...

Memfilter data untuk baris di mana 'Request method' adalah 'GET'...

Berhasil memfilter data dan menyimpannya ke 'method_get_only.csv'.
Pratinjau data yang telah difilter:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers)
0,65.55.147.227,-,-,2009-10-15T02:00:24Z,GET,/index.html,HTTP/1.1,200,21878
1,65.55.86.34,-,-,2009-10-15T02:00:58Z,GET,/index.html,HTTP/1.1,200,1416
2,148.188.55.88,-,-,2009-10-15T02:01:41Z,GET,/faq.html,HTTP/1.1,200,10946
3,66.249.139.233,-,-,2009-10-15T02:02:09Z,GET,/faq.html,HTTP/1.1,200,17247
4,72.30.50.248,-,-,2009-10-15T02:02:13Z,GET,/index.html,HTTP/1.0,200,7883

## **Membersihkan Format Waktu di Kolom Request Time menjadi tanggal dan waktunya**

In [7]:
file_name = "method_get_only.csv"
target_column = "Request time"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Tampilkan contoh format asli (opsional)
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    # 4. Bersihkan format datetime
    print(f"Mengubah format kolom '{target_column}'...")
    df[target_column] = df[target_column].str.replace('T', ' ', regex=False)
    df[target_column] = df[target_column].str.replace('Z', '', regex=False)

    # 5. Simpan ke CSV baru
    output_filename = "request_time_cleaned.csv"
    df.to_csv(output_filename, index=False)

    # 6. Tampilkan hasil dalam tabel rapi
    print(f"\nBerhasil mengubah format data dan menyimpannya ke '{output_filename}'.")
    print("Pratinjau data yang telah diubah:")
    display(df.head())

Memuat data dari method_get_only.csv...
Format asli (baris pertama): 2009-10-15T02:00:24Z
Mengubah format kolom 'Request time'...

Berhasil mengubah format data dan menyimpannya ke 'request_time_cleaned.csv'.
Pratinjau data yang telah diubah:

,Remote host,Remote logname,Remote user,Request time,Request method,Request URI,Request Protocol,Status,Size of response (incl. headers)
0,65.55.147.227,-,-,2009-10-15 02:00:24,GET,/index.html,HTTP/1.1,200,21878
1,65.55.86.34,-,-,2009-10-15 02:00:58,GET,/index.html,HTTP/1.1,200,1416
2,148.188.55.88,-,-,2009-10-15 02:01:41,GET,/faq.html,HTTP/1.1,200,10946
3,66.249.139.233,-,-,2009-10-15 02:02:09,GET,/faq.html,HTTP/1.1,200,17247
4,72.30.50.248,-,-,2009-10-15 02:02:13,GET,/index.html,HTTP/1.0,200,7883

# **TUGAS NASA**

## **CARA KE-1**

In [8]:
file_name = "data.csv"

print(f"Memuat data dari {file_name}...")

# 🔍 Deteksi pemisah otomatis: pilih yang paling banyak dipakai
with open(file_name, 'r') as f:
    sample = f.read(2048)

delimiter = ';' if sample.count(';') > sample.count(',') else ','

print(f"Delimiter terdeteksi: '{delimiter}'")

# 📌 Baca ulang file dengan pemisah yang benar
df = pd.read_csv(file_name, sep=delimiter)

# 📌 Tampilkan kolom untuk verifikasi
print("\nDaftar kolom terdeteksi:")
print(df.columns.tolist())

print("\nInfo data:")
display(df.info())

print("\nData Head:")
display(df.head()) # Memperbaiki error dengan memanggil .head()

# ============================================================
# 2. FILTER REQUEST .html
# ============================================================

target_column = "url"

if target_column not in df.columns:
    print(f"\n❌ Kolom '{target_column}' tidak ditemukan! Pilih salah satu dari ini:")
    print(df.columns.tolist())
else:
    print(f"\nMemfilter baris dimana '{target_column}' diakhiri '.html'...")

    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()
    output_filename = "html_requests_only_NASA.csv"

    filtered_df.to_csv(output_filename, sep=delimiter, index=False)

    print(f"✅ Hasil berhasil disimpan ke {output_filename}")
    display(filtered_df.head())

Memuat data dari data.csv...
Delimiter terdeteksi: ','

Daftar kolom terdeteksi:
['Unnamed: 0', 'host', 'time', 'method', 'url', 'response', 'bytes']

Info data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2965561 entries, 0 to 2965560
Data columns (total 7 columns):
 #   Column      Dtype
---  ------      -----
 0   Unnamed: 0  int64
 1   host        object
 2   time        int64
 3   method      object
 4   url         object
 5   response    int64
 6   bytes       int64
dtypes: int64(4), object(3)
memory usage: 158.4+ MB

None

Data Head:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

Memfilter baris dimana 'url' diakhiri '.html'...
✅ Hasil berhasil disimpan ke html_requests_only_NASA.csv

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
6,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
12,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
13,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
23,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

## **Memfilter Request yang Mengakses Halaman dengan Ekstensi .html**

In [9]:
file_name = "data.csv"

print(f"Memuat data dari {file_name}...")

# 🔍 Deteksi delimiter otomatis
with open(file_name, 'r') as f:
    sample = f.read(3000)

delimiter = ';' if sample.count(';') > sample.count(',') else ','

print(f"Delimiter terdeteksi: '{delimiter}'")

# 📌 Baca ulang file DENGAN delimiter benar TANPA index_col
df = pd.read_csv(file_name, sep=delimiter)

print("\nDaftar kolom terdeteksi:")
print(df.columns.tolist())

print("\nPreview data:")
display(df.head())

Memuat data dari data.csv...
Delimiter terdeteksi: ','

Daftar kolom terdeteksi:
['Unnamed: 0', 'host', 'time', 'method', 'url', 'response', 'bytes']

Preview data:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866
2,2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363
3,3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234
4,4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786

## **Memfilter Log dengan Status Response 200**

In [10]:
file_name = "html_requests_only_NASA.csv"

print(f"Memuat data dari {file_name}...")

# Coba baca otomatis: jika gagal, pakai delimiter lain
try:
    df = pd.read_csv(file_name)
except:
    df = pd.read_csv(file_name, sep=';')

print("\nDaftar kolom:", df.columns.tolist())

# Pastikan kolom 'response' ada
if "response" not in df.columns:
    raise ValueError("❌ Kolom 'response' tidak ditemukan di dataset!")

# Pastikan kolom numerik
df["response"] = pd.to_numeric(df["response"], errors='coerce')

# Filter hanya status code 200
filtered_df = df[df["response"] == 200].copy()

# Simpan hasil filter
output_filename = "status_200_only_NASA.csv"
filtered_df.to_csv(output_filename, index=False)

print(f"\n Berhasil memfilter data dengan response=200.")
print(f" File disimpan sebagai: {output_filename}")

display(filtered_df.head())

Memuat data dari html_requests_only_NASA.csv...

Daftar kolom: ['Unnamed: 0', 'host', 'time', 'method', 'url', 'response', 'bytes']

 Berhasil memfilter data dengan response=200.
 File disimpan sebagai: status_200_only_NASA.csv

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

## **Memfilter Request yang Menggunakan Metode GET**

In [11]:
file_name = "status_200_only_NASA.csv"
filter_value = "GET"
target_column = "method"

print(f"Memuat data dari {file_name}...")

# Gunakan sep=None -> delimiter otomatis
df = pd.read_csv(file_name, sep=None, engine="python")

print("\nKolom terdeteksi:", df.columns.tolist())

# Pastikan kolom ada
if target_column not in df.columns:
    raise ValueError(f"❌ Kolom '{target_column}' tidak ditemukan di CSV!")

# Filter baris method == GET
print(f"\nMemfilter baris di mana '{target_column}' == '{filter_value}' ...")
filtered_df = df[df[target_column] == filter_value].copy()

# Simpan hasil
output_filename = "method_get_only_NASA.csv"
filtered_df.to_csv(output_filename, index=False)

print(f"\n✅ Berhasil memfilter data dan menyimpannya ke {output_filename}.")
print("Pratinjau data hasil filter:")
display(filtered_df.head())

Memuat data dari status_200_only_NASA.csv...

Kolom terdeteksi: ['Unnamed: 0', 'host', 'time', 'method', 'url', 'response', 'bytes']

Memfilter baris di mana 'method' == 'GET' ...

✅ Berhasil memfilter data dan menyimpannya ke method_get_only_NASA.csv.
Pratinjau data hasil filter:

,Unnamed: 0,host,time,method,url,response,bytes
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665

## **Melakukan perubahan di Request Time menjadi tanggal dan waktunya**

In [12]:
file_name = "method_get_only_NASA.csv"

print(f"Memuat data dari {file_name}...")

# BACA SEBAGAI CSV NORMAL (TIDAK ADA ';')
df = pd.read_csv(file_name)

print("Kolom terdeteksi:", df.columns.tolist())

target_column = "time"

if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    print(f"Mengonversi kolom '{target_column}' ke datetime...")

    df["datetime_readable"] = pd.to_datetime(df[target_column], unit="s")

    output_filename = "time_converted_NASA.csv"
    df.to_csv(output_filename, index=False)

    print(f"\nBerhasil menyimpan ke {output_filename}")
    display(df.head())

Memuat data dari method_get_only_NASA.csv...
Kolom terdeteksi: ['Unnamed: 0', 'host', 'time', 'method', 'url', 'response', 'bytes']
Format asli (baris pertama): 805465029
Mengonversi kolom 'time' ke datetime...

Berhasil menyimpan ke time_converted_NASA.csv

,Unnamed: 0,host,time,method,url,response,bytes,datetime_readable
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067,1995-07-11 12:17:09
1,6,***.novo.dk,805465068,GET,/shuttle/missions/missions.html,200,8678,1995-07-11 12:17:48
2,12,***.novo.dk,805465381,GET,/shuttle/resources/orbiters/columbia.html,200,6922,1995-07-11 12:23:01
3,13,***.novo.dk,807951768,GET,/shuttle/missions/sts-69/mission-sts-69.html,200,11264,1995-08-09 07:02:48
4,23,***.novo.dk,807951938,GET,/shuttle/countdown/liftoff.html,200,4665,1995-08-09 07:05:38

## **Membuat Kolom pada session berdasarkan Host, Mengurutkan Berdasarkan Waktu, dan Menyimpan Tabel Final**

In [13]:
file_name = "time_converted_NASA.csv"
col_ip = "host"
col_time = "datetime_readable"
new_col_name = "SESSION"

print(f"Memuat data dari {file_name}...")

# 1. Baca file dengan PEMISAH OTOMATIS (jangan pakai ; )
df = pd.read_csv(file_name)

print("Kolom terdeteksi:", df.columns.tolist())

# 2. Cek kolom wajib
if col_ip not in df.columns or col_time not in df.columns:
    raise ValueError(f"Kolom '{col_ip}' atau '{col_time}' tidak ditemukan!")

# 3. Konversi kolom waktu ke datetime
df[col_time] = pd.to_datetime(df[col_time], errors='coerce')

# 4. Buat kolom SESSION
df[new_col_name] = df[col_ip].astype('category').cat.codes + 1

# 5. Sortir berdasarkan SESSION & waktu
df_sorted = df.sort_values(by=[new_col_name, col_time])

# 6. Hapus kolom time lama jika masih ada
if "time" in df_sorted.columns:
    df_sorted = df_sorted.drop(columns=["time"])

# 7. Simpan
output_filename = "session_data_full_NASA.csv"
df_sorted.to_csv(output_filename, index=False)

print(f"\nSukses! File disimpan sebagai {output_filename}")
display(df_sorted[[new_col_name, col_ip, col_time, "url"]].head())

Memuat data dari time_converted_NASA.csv...
Kolom terdeteksi: ['Unnamed: 0', 'host', 'time', 'method', 'url', 'response', 'bytes', 'datetime_readable']

Sukses! File disimpan sebagai session_data_full_NASA.csv

,SESSION,host,datetime_readable,url
0,1,***.novo.dk,1995-07-11 12:17:09,/ksc.html
1,1,***.novo.dk,1995-07-11 12:17:48,/shuttle/missions/missions.html
2,1,***.novo.dk,1995-07-11 12:23:01,/shuttle/resources/orbiters/columbia.html
3,1,***.novo.dk,1995-08-09 07:02:48,/shuttle/missions/sts-69/mission-sts-69.html
4,1,***.novo.dk,1995-08-09 07:05:38,/shuttle/countdown/liftoff.html

## **CARA KE-2**

In [14]:
import pandas as pd

# Path dataset
file_path = "data.csv"

df = pd.read_csv(file_path, sep=',') # Mengoreksi pemisah dari ';' menjadi ','

# Convert time
df["Timestamp"] = pd.to_datetime(df["time"], unit="s")

# Rename
df.rename(columns={"host": "Host"}, inplace=True)

df.head()

,Unnamed: 0,Host,time,method,url,response,bytes,Timestamp
0,0,***.novo.dk,805465029,GET,/ksc.html,200,7067,1995-07-11 12:17:09
1,1,***.novo.dk,805465031,GET,/images/ksclogo-medium.gif,200,5866,1995-07-11 12:17:11
2,2,***.novo.dk,805465051,GET,/images/MOSAIC-logosmall.gif,200,363,1995-07-11 12:17:31
3,3,***.novo.dk,805465053,GET,/images/USA-logosmall.gif,200,234,1995-07-11 12:17:33
4,4,***.novo.dk,805465054,GET,/images/NASA-logosmall.gif,200,786,1995-07-11 12:17:34

## **Konversi URL Menjadi Label Huruf**

In [15]:
def num_to_letters(n):
    """Konversi angka ke huruf: 0→A, 1→B, ..., 25→Z, 26→AA, dst."""
    result = ""
    n += 1
    while n > 0:
        n -= 1
        result = chr(65 + (n % 26)) + result
        n //= 26
    return result

# --- Hasil Langsung ---
[num_to_letters(i) for i in range(10)]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

## **Pembentukan Web Usage Session**

In [16]:
def num_to_letters(n):
    string = ""
    while n >= 0:
        string = chr(n % 26 + ord('A')) + string
        n = n // 26 - 1
    return string

def process_web_usage(df):
    """
    Membentuk sesi web usage 20 menit per host.
    URL diganti dengan huruf A-Z.
    """

    # Buat mapping URL → huruf
    unique_urls = df["url"].unique() # Corrected 'URL' to 'url'
    url_map = {url: num_to_letters(i) for i, url in enumerate(unique_urls)}
    df["URL_Label"] = df["url"].map(url_map) # Corrected 'URL' to 'url'

    df = df.sort_values(by=["Host", "Timestamp"])

    results = []

    for host, group in df.groupby("Host"):
        group = group.sort_values("Timestamp").reset_index(drop=True)

        sessions = []
        cur_session = []
        prev_time = None

        for _, row in group.iterrows():
            ts = row["Timestamp"]
            label = row["URL_Label"]

            if prev_time is None:
                cur_session.append((ts, label))
            else:
                delta = (ts - prev_time).total_seconds() / 60

                # aturan sesi 20 menit
                if delta > 20:
                    sessions.append(cur_session)
                    cur_session = [(ts, label)]
                else:
                    cur_session.append((ts, label))

            prev_time = ts

        if cur_session:
            sessions.append(cur_session)

        results.append({
            "Host": host,
            "Sessions": sessions
        })

    return results, url_map


# --- Hasil Langsung ---
results, url_map = process_web_usage(df)
results[:1]   # tampilkan contoh 1 host pertama

[{'Host': '***.novo.dk',
  'Sessions': [[(Timestamp('1995-07-11 12:17:09'), 'A'),
    (Timestamp('1995-07-11 12:17:11'), 'B'),
    (Timestamp('1995-07-11 12:17:31'), 'C'),
    (Timestamp('1995-07-11 12:17:33'), 'D'),
    (Timestamp('1995-07-11 12:17:34'), 'E'),
    (Timestamp('1995-07-11 12:17:38'), 'F'),
    (Timestamp('1995-07-11 12:17:48'), 'G'),
    (Timestamp('1995-07-11 12:17:51'), 'H'),
    (Timestamp('1995-07-11 12:19:13'), 'I'),
    (Timestamp('1995-07-11 12:19:17'), 'E'),
    (Timestamp('1995-07-11 12:22:03'), 'J'),
    (Timestamp('1995-07-11 12:22:08'), 'K'),
    (Timestamp('1995-07-11 12:23:01'), 'L')],
   [(Timestamp('1995-08-09 07:02:48'), 'M'),
    (Timestamp('1995-08-09 07:02:55'), 'N'),
    (Timestamp('1995-08-09 07:03:02'), 'I'),
    (Timestamp('1995-08-09 07:03:06'), 'J'),
    (Timestamp('1995-08-09 07:03:12'), 'K'),
    (Timestamp('1995-08-09 07:03:52'), 'O'),
    (Timestamp('1995-08-09 07:04:08'), 'P'),
    (Timestamp('1995-08-09 07:04:24'), 'E'),
    (Timestamp('1995-08-09 07:05:07'), 'Q'),
    (Timestamp('1995-08-09 07:05:14'), 'R'),
    (Timestamp('1995-08-09 07:05:38'), 'S'),
    (Timestamp('1995-08-09 07:06:21'), 'T'),
    (Timestamp('1995-08-09 07:07:24'), 'U'),
    (Timestamp('1995-08-09 07:07:40'), 'V'),
    (Timestamp('1995-08-09 07:07:58'), 'W'),
    (Timestamp('1995-08-09 07:08:22'), 'X')]]}]

## **Membentuk Tabel Web Usage (Host – Session – Timestamp – Page)**

In [17]:
url_mapping_df = pd.DataFrame([
    {"URL": url, "Label": label}
    for url, label in url_map.items()
])

url_mapping_df

                                                   URL Label
0                                            /ksc.html     A
1                           /images/ksclogo-medium.gif     B
2                         /images/MOSAIC-logosmall.gif     C
3                            /images/USA-logosmall.gif     D
4                           /images/NASA-logosmall.gif     E
..                                                 ...   ...
360                                  /finance/book.gif    MW
361                                  /finance/tour.gif    MX
362                              /finance/brrow_1t.gif    MY
363  /shuttle/missions/sts-71/images/KSC-95EC-0423.jpg    MZ
364         /software/winvn/faq/WINVNFAQ-Contents.html    NA

[365 rows x 2 columns]

## **Ringkasan Total Sesi Per Host**

In [18]:
table_rows = []

for item in results:
    host = item["Host"]
    sessions = item["Sessions"]

    for session_idx, session in enumerate(sessions, start=1):
        for ts, label in session:
            table_rows.append({
                "Host": host,
                "Session": session_idx,
                "Timestamp": ts,
                "Page": label
            })

usage_table = pd.DataFrame(table_rows)

usage_table

                            Host  Session           Timestamp Page
0                    ***.novo.dk        1 1995-07-11 12:17:09    A
1                    ***.novo.dk        1 1995-07-11 12:17:11    B
2                    ***.novo.dk        1 1995-07-11 12:17:31    C
3                    ***.novo.dk        1 1995-07-11 12:17:33    D
4                    ***.novo.dk        1 1995-07-11 12:17:34    E
...                          ...      ...                 ...  ...
2965556  zzzzzzzz.mindspring.com        1 1995-08-27 21:52:53    M
2965557  zzzzzzzz.mindspring.com        1 1995-08-27 21:52:55    N
2965558  zzzzzzzz.mindspring.com        1 1995-08-27 21:53:11    I
2965559  zzzzzzzz.mindspring.com        1 1995-08-27 21:53:11    J
2965560  zzzzzzzz.mindspring.com        1 1995-08-27 21:53:12    K

[2965561 rows x 4 columns]

In [19]:
session_summary = usage_table.groupby("Host")["Session"].nunique().reset_index()
session_summary.rename(columns={"Session": "Total Sessions"}, inplace=True)

session_summary

                                   Host  Total Sessions
0                           ***.novo.dk               2
1               001.msy4.communique.net               1
2                        007.thegap.com               5
3       01-dynamic-c.wokingham.luna.net               6
4                 01.ts01.zircon.net.au               1
...                                 ...             ...
135263        zzsmiffs.slip.cc.uq.oz.au               1
135264        zztduffy.slip.cc.uq.oz.au               1
135265                zzyzx.demon.co.uk               1
135266             zzz.pe.u-tokyo.ac.jp               2
135267          zzzzzzzz.mindspring.com               1

[135268 rows x 2 columns]

## **MEMBANGUN TABEL BINARY PER HALAMAN**

In [ ]:
# 5. MEMBANGUN TABEL BINARY PER HALAMAN (A=1, lainnya=0)

import pandas as pd # Import pandas for DataFrame operations

# --- Start code to ensure 'df' is available ---
# Path dataset
file_path = "data.csv"

# Load df and preprocess (copied from cell 0Z9oSXRTOQHd)
df = pd.read_csv(file_path, sep=',')

# Convert time
df["Timestamp"] = pd.to_datetime(df["time"], unit="s")

# Rename
df.rename(columns={"host": "Host"}, inplace=True)
# --- End code to ensure 'df' is available ---

def num_to_letters(n):
    string = ""
    while n >= 0:
        string = chr(n % 26 + ord('A')) + string
        n = n // 26 - 1
    return string

def process_web_usage(df):
    """
    Membentuk sesi web usage 20 menit per host.
    URL diganti dengan huruf A-Z.
    """

    # Buat mapping URL → huruf
    unique_urls = df["url"].unique()
    url_map = {url: num_to_letters(i) for i, url in enumerate(unique_urls)}
    df["URL_Label"] = df["url"].map(url_map)

    df = df.sort_values(by=["Host", "Timestamp"])

    results = []

    for host, group in df.groupby("Host"):
        group = group.sort_values("Timestamp").reset_index(drop=True)

        sessions = []
        cur_session = []
        prev_time = None

        for _, row in group.iterrows():
            ts = row["Timestamp"]
            label = row["URL_Label"]

            if prev_time is None:
                cur_session.append((ts, label))
            else:
                delta = (ts - prev_time).total_seconds() / 60

                # aturan sesi 20 menit
                if delta > 20:
                    sessions.append(cur_session)
                    cur_session = [(ts, label)]
                else:
                    cur_session.append((ts, label))

            prev_time = ts

        if cur_session:
            sessions.append(cur_session)

        results.append({
            "Host": host,
            "Sessions": sessions
        })

    return results, url_map

def build_binary_table(results, url_map):
    all_labels = sorted(url_map.values())  # A, B, C, ...
    rows = []

    for host_data in results:
        host = host_data["Host"]

        for session in host_data["Sessions"]:
            for ts, label in session:

                # buat baris kosong (semua 0)
                row = {l: 0 for l in all_labels}

                # halaman yang dikunjungi = 1
                row[label] = 1

                # tambahkan kolom lain
                row["Time"] = ts.strftime("%H:%M")
                row["Host"] = host

                rows.append(row)

    return pd.DataFrame(rows)

# Ensure 'results' and 'url_map' are defined. If not, re-generate from 'df'.
# Note: 'df' is now guaranteed to be available from the code above.
if 'results' not in locals() or 'url_map' not in locals():
    print("Warning: 'results' or 'url_map' not found. Attempting to re-generate from 'df'...")
    # 'process_web_usage' and 'num_to_letters' are now defined in this cell
    results, url_map = process_web_usage(df)

binary_table = build_binary_table(results, url_map)

print("=== Tabel Binary Halaman Dikunjungi ===")
display(binary_table.head(20))

# Simpan CSV bila diperlukan
binary_table.to_csv("binary_web_usage.csv", index=False)

Warning: 'results' or 'url_map' not found. Attempting to re-generate from 'df'...

In [ ]:
from openpyxl import Workbook

# Buat workbook baru
wb = Workbook()

# ----------------------------
# Sheet 1: URL Mapping
# ----------------------------
ws1 = wb.active
ws1.title = "URL Mapping"

# Header
ws1.append(list(url_mapping_df.columns))

# Isi data
for row in url_mapping_df.itertuples(index=False):
    ws1.append(list(row))

# ----------------------------
# Sheet 2: Web Usage Sessions
# ----------------------------
ws2 = wb.create_sheet("Web Usage Sessions")

ws2.append(list(usage_table.columns))
for row in usage_table.itertuples(index=False):
    ws2.append(list(row))

# ----------------------------
# Sheet 3: Session Summary
# ----------------------------
ws3 = wb.create_sheet("Session Summary")

ws3.append(list(session_summary.columns))
for row in session_summary.itertuples(index=False):
    ws3.append(list(row))

# ----------------------------
# Save file
# ----------------------------
output_path = "/content/web_usage_complete.xlsx"
wb.save(output_path)

print("✔ File Excel lengkap berhasil dibuat:")
print(output_path)